name: CD Pipeline
run-name: ${{ github.actor }} is Deploying 🚀
on:
    push: 
        branches:
            - master
        tags:
            - '*'
    workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
        IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Download artifact
          uses: actions/download-artifact@v2
          with:
            name: Package
             
        - name: Copy artifact to EC2
          run: |
            scp -i swap_key_spain.pem target/*jar ubuntu@18.101.7.150:/home/ubuntu/app

      # SSH into EC2 and start the application
        - name: SSH into EC2 and start application
          run: |
            ssh -i swap_key_spain.pem ubuntu@18.101.7.150:/home/ubuntu/app <<EOF
            cd /home/ubuntu/app
            java -jar target/*.jar
            EOF

        